CCI-MOC/esi-pilot

esi_report.sh
I have changed to the file format for nodes-daily and leases-current reports from log file to csv file.
Further, after comparing with curator report that Gagan sent, I see that the following fields are missing in our reports
1. frequency
2. interval start
3. interval end
However, I am not sure whether these fields are required for ESI reports since the file name is self explanatory. Please let me know what you think about this and whether I should make any further changes!
I am attaching curator report for reference
[report-day-2022-08-22 00 00 00+00 00.csv](https://github.com/CCI-MOC/esi-pilot/files/9425323/report-day-2022-08-22.00.00.00%2B00.00.csv)
=> Changes to make reports inline with curator

ansible-deployment/volume/tasks/main.yaml
I didn't add ceph.conf and ceph.client.esi.keyring into this repo because I'm not sure if they contain credentials. But when we run ansible-playbooks, we need to add these files into ansible-deployment/volume/tasks.
=> copy ceph config files to volume container

custom_network_data.yaml
These values were incorrectly set to overcloud networks, causing issues during updates.
=> Update custom_network_data.yaml to reflect undercloud networks

bm_inventory_oct.json
These are the initial imports for cha3 and cha4 in OCT4 (cha1 and cha2 were not added to the ESI pool). Root passwords have been obfuscated.
=> Added cha3 and cha4 in OCT4

bm_inventory_r4pac21.json
This PR adds the bare-metal manifest for all the ready nodes in R4-PA-C21. There are several nodes in that rack that are missing from this manifest because there is some missing information or broken hardware, which will be added to the same file in a future PR.
Some notes:
* iDrac admin password is redacted
* All nodes have been firmware updated to the latest version, configured to pxe boot, and ipmi over lan enabled. BIOS is the boot mode.
* The IPMI port comes from the idrac IP. For example, is the ip of the node is `10.2.10.161`, the port is `10161`. Hope this works!
* It's possible some of the switchports are swapped. ie. the first port actually goes to the 2nd switch etc. If this is the case I will swap the connections in person, so the manifest will stay the same.
Each node is …
=> R4-PA-C21 Initial Manifest

policy_files/policy.yaml
This change is needed for tenants to use tools such as Metalsmith.
=> Updated neutron policy file to allow tenants to modify port binding host_id

esi-custom.yaml
Removing 465-499, as none are in use and they are needed elsewhere.
=> Update vlan range

ansible-deployment/switch/tasks/switches.j2
As discussed on Slack, this is the change that happened during maintenance yesterday for `switch1`.
=> Updated host for switch1

nodes/bm_inventory_r4pac08.json, nodes/bm_inventory_r4pac10.json, nodes/bm_inventory_r4pac21.json, nodes/bm_inventory_r4pac22.json, nodes/bm_inventory_r4pac24.json
This PR changes the relevant manifest properties for the nvme nodes (`U29-S1`) in each rack (These nodes are already in ESI). This includes
* Adding root disk wwn property since it otherwise defaults to boot off of the nvme drives
* Setting resource class to `fc830-nvme`
* Adding 2x interfaces for the 2x 40G nics on each node
The WWN is the only property I manually applied already, everything else still needs to be applied
=> Adding NVMe Nodes

nodes/node-check.py
The `inspect` option of the node-check.py script does not bother to move the node to manageable before inspection; this will immediately fail inspection. This fix changes that.
=> Move node to manageable before inspection

ansible-deployment/switch/tasks/switches.j2, nodes/bm_inventory_r4pac04.json
These are 2 oddball nodes with no model number (custom built), hence the weird resource class. This PR also adds the TORS in that rack (which will be used for other nodes momentarily)
@tzumainn these are the UEFI nodes I was talking about, so there may be some extra steps here
=> Adding 2 new research nodes

nodes/bm_inventory_r4pac04.json
Closes CCI-MOC/ops-issues#1252, I've added the manifest for the FD332 nodes. They have not been tested.
=> Add Peter FD332 nodes to ESI

openstack_commands/network.sh
Added NESE vl211, which is our side of the peering w/ NESE. Also adds static routes for hosts to be able to reach NESE ceph.
=> added NESE vl211 to networks.sh

nodes/bm_inventory_r8pac23.json
Since the board was replaced on these the MACs changed.
**NOTE: these node are not yet reachable on their BMC IPs, the dhcp needs to catch up, should happen soon.**
=> Updated MACs for R8-PA-C23-U26 and U28

openstack_commands/network.sh, openstack_commands/owned_networks.sh
This is for: https://github.com/nerc-project/operations/issues/726
This network should be owned by `nerc-admins`, I added the `--project` argument for that. The router is external, ESI will only provide DHCP. This network will need to be shared to other projects in ESI (as outlined in the issue) - since nerc-admins owns it I thought it may not be a great idea to add the shares in here too but I'm open to other ideas.
For the sharing - it will likely be a combination of nerc-admins members and esi admins assigning projects via sharing, though nerc-admins should always have a way to change that from their end
=> Added NERC Infra Routed Network

nodes/bm_inventory_r8pac23.json
MOC-R8PAC23U25 had its board swapped so the mac address of the interface needs to be updated.
=> Fixing MOC-R8PAC23U25 A100 Node

ansible-deployment/ironic_config/tasks/accelerators.yaml, ansible-deployment/switch/tasks/switches.j2, nodes/bm_inventory_r4pac02.json
Single node that is likely temporary for a few months.
I'm not sure what the device id and vendor id is. @tzumainn do you know how to find that info? Do we have to boot the node for that?
=> Adding AMD Mi210 GPU Node

esi-custom.yaml
This will allow users to create neutron networks supporting
jumbo frames, useful for storage-related needs.
=> Set NeutronGlobalPhysnetMtu to 9000

nodes/bm_inventory_r4pcc02.json, nodes/bm_inventory_r4pcc04.json
@tzumainn I didn't include port information for these because we are planning to have ESI handle only the leasing of these - I assume that's okay? I'm not sure what the port configuration will look like by the time we get ESI to manage it (whether it will be aggregated or not etc.) so I figured it doesn't make sense to map all that out now.
=> Adding H100 Nodes to ESI

ansible-deployment/ironic_config/tasks/accelerators.yaml, ansible-deployment/switch/tasks/switches.j2, custom-dockerfiles/neutron-server/Dockerfile, nodes/bm_inventory_r4pcc02.json, nodes/bm_inventory_r4pcc04.json
* Adds 2x top-of-rack switches
* No become method because these don't work the same as OS9
* Adds port info for every node (verified with switch mac table)
=> Adding H100 Networking
